// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

/************************************************************/
/**
 * La clase Frase se ocupará de almacenar diferentes frases para el 
  * juego, contendrá distintos métodos que ayudarán al proceso 
  * y se ocuparán de seleccionar la frase de forma aleatoria.
  * 
 */
public class Frase {
	/**
	 * 
	 */
	private String[] frases;

	/**
	 * Devuelve una frase aleatoria sacada del array frases.
	 */
	public void elegirFrase() {
	}
};
