// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

import RootElement.Partida;

/************************************************************/
/**
 * La clase Munieco almacena los datos necesarios para poder gestionar al muñeco del juego.
 */
public class Horca {
	/**
	 * Número de fallos que lleva el usuari, vamos a permitir 6 fallos.
	 */
	private int[] fallos;
	/**
	 * 
	 */
	private boolean brazoDerecho;
	/**
	 * 
	 */
	private boolean brazoIzquierdo;
	/**
	 * 
	 */
	private boolean piernaDerecha;
	/**
	 * 
	 */
	private boolean piernaIzquierda;
	/**
	 * 
	 */
	private boolean cuerpo;
	/**
	 * 
	 */
	public Partida partida;

	/**
	 * Dibuja o elimina las partes del cuepo del muñeco.
	 */
	public void dibujar() {
	}

	/**
	 * Aumenta el contador de fallos.
	 */
	public void incrementarFallo() {
	}

	/**
	 * Comprueba si los fallos han llegado al límite establecido, si es así, la partida terminará, en caso contrario seguirá
	 * @return ganado 
	 */
	public boolean comprobarSiPerdido() {
	}
};
