// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

/************************************************************/
/**
 * La clase Munieco almacena los datos necesarios para poder gestionar al muñeco del juego.
 */
public class Munieco {
	/**
	 * 
	 */
	private int[] vida;
	/**
	 * 
	 */
	private boolean brazoDerecho;
	/**
	 * 
	 */
	private boolean brazoIzquierdo;
	/**
	 * 
	 */
	private boolean piernaDerecha;
	/**
	 * 
	 */
	private boolean piernaIzquierda;
	/**
	 * 
	 */
	private boolean cuerpo;

	/**
	 * Dibuja o elimina las partes del cuepo del muñeco.
	 */
	public void dibujar() {
	}
};
