// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

import RootElement.Frase;

/************************************************************/
/**
 * La clase principal, Partida. Contiene datos sobre la partida que está en curso, tambén tiene un método que es un contador de puntos del jugador.
 */
public class Partida {
	/**
	 * 
	 */
	private String nombreJugador;
	/**
	 * 
	 */
	private int puntaje;
	/**
	 * 
	 */
	public Frase frase;
	/**
	 * 
	 */
	private int limiteFrases;
	/**
	 * 
	 */
	private int tiempoPorFrase;

	/**
	 * Cuenta los puntos en la partida dependiendo del puntuaje
	 */
	public void contadorPuntos() {
	}
};
