// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package ahorcado;

/************************************************************/
/**
 * La clase Munieco almacena los datos necesarios para poder gestionar al muñeco
 * del juego.
 */
public class Horca {
	protected static final int MAX_FALLOS = 6;
	/**
	 * Número de fallos que lleva el usuari, vamos a permitir 6 fallos.
	 */
	private int fallos;

	/**
	 * Dibuja o elimina las partes del cuepo del muñeco.
	 */

	/**
	 * 
	 */

	public Horca() {
		fallos = 0;
	}

	public void dibujar() {
		System.out.println("Fallos: " + fallos);
	}

	/**
	 * Aumenta el contador de fallos.
	 */
	public void incrementarFallo() {
		fallos++;
	}

	/**
	 * Comprueba si los fallos han llegado al límite establecido, si es así, la
	 * partida terminará, en caso contrario seguirá
	 * 
	 * @return ganado
	 */
	public boolean comprobarSiPerdido() {
		return (fallos == MAX_FALLOS);
	}

	public int getFallos() {
		return fallos;
	}

};
