// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ahorcado;

/************************************************************/
/**
 * La clase Frase se ocupará de almacenar diferentes frases para el juego,
 * contendrá distintos métodos que ayudarán al proceso y se ocuparán de
 * seleccionar la frase de forma aleatoria.
 * 
 */
public class Palabra {
	/**
	 * Palabra que ha sido escogida para adivinar.
	 * 
	 */
	private String palabraOculta;
	/**
	 * Son las letras que el jugador ha dicho pero no estaban en la palabra.
	 */
	private char[] letrasFallidas;
	/**
	 * Son las letras que ha dicho el jugador y estaban en la palabra.
	 */
	private char[] letrasDescubiertas;

	/**
	 * Devuelve una frase aleatoria sacada del array frases.
	 */
	public String elegirPalabra() {
		String[] palabras = { "Jirafa", "Perro", "Gato", "Gallo", "Elefante", "Rata", "Tortuga" };
		String elegida = palabras[(int) (Math.random() * (palabras.length - 1))];

		return elegida;

	}

	/**
	 * Comprueba si existe la letra en la palabra oculta.
	 * 
	 * @param letra
	 *            Letra a comprobar si existe o no en la palabra a adivinar
	 * @return estaba Devuelve true si la letra está al menos una vez en la
	 *         palabra oculta y false en caso contrario
	 * 
	 */
	public boolean comrpobarLetra(char letra) {
		if (palabraOculta.indexOf(letra) == -1)
			return false;
		else
			return true;
	}

	/**
	 * Muestra el reusltado de la palabra, con sus letras adivinadas y el
	 * diseño.
	 */
	public void mostrarResultados() {
	}

	/**
	 * 
	 * @return ganado
	 */
	public boolean comprobarSiGanador() {
	}

	/**
	 * Comprueba si la palabra propuesta por el jugador coincide con la palabra
	 * oculta (quiero resolver).
	 * 
	 * @param palabra
	 * @return adivinada Adivinada es verdadero si la palabra coincide con la
	 *         que buscábamos.
	 */
	public boolean comprobarPalabra(String palabra) {
	}
};
