// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ahorcado;

import java.util.*;
import java.lang.Character;

/************************************************************/
/**
 * La clase principal, Partida. Contiene datos sobre la partida que está en
 * curso, tambén tiene un método que es un contador de puntos del jugador.
 * 
 * @author Juan y Patryk.
 */
public class Partida {
	/**
	 * Nombre del jugador que se usará para mostrar ciertos datos en la partida.
	 */
	private static String nombreJugador;
	/**
	 * 
	 */
	public static Horca horca;
	/**
	 * 
	 */
	public static Palabra palabra;

	/**
	 * Cuenta los puntos en la partida dependiendo del puntuaje.
	 */
	public void contadorPuntos() {
	}

	/**
	 * Muestra el estado de la horca y los resultados de la palabra.
	 */
	public static void mostrarProgreso() {

		horca.dibujar();
		palabra.mostrarResultados();
	}

	/**
	 * Solicita una letra al usuario.
	 * 
	 * @return un caracter que posteriormente se insertará en al array
	 *         correspondiente.
	 */
	public static char pedirLetra() {

		Scanner entrada = new Scanner(System.in);

		System.out.print("Introduce una letra: ");
		char letra = entrada.nextLine().charAt(0);

		return Character.toLowerCase(letra);
	}

	/**
	 * Pide la respuesta al jugador.
	 * 
	 * @return palabra true si el jugador ha acertado o false en caso contrario.
	 */
	public static boolean resolver() {
		Scanner entrada = new Scanner(System.in);

		System.out.print("Introduce la respuesta: ");
		return palabra.comprobarPalabra(entrada.nextLine().toLowerCase());

	}

	/**
	 * Comprueba tanto si hemos agotado los fallos como si hemos acertado todas
	 * las letras.
	 * 
	 * @return fin true si hemos ganado o perdido, false si todavía jugamos.
	 */
	public static boolean comprobarFinal() {
		return horca.comprobarSiPerdido() || palabra.comprobarSiGanado();

	}

	/**
	 * Menú principal del juego donde el jugador podrá inteerectuar con la
	 * partida.
	 * 
	 * @return devuelve el valor para operar con el menú.
	 */
	public static int elegirDelMenu() {
		Scanner entrada = new Scanner(System.in);

		System.out.println("\n*--------------------------------*");
		System.out.println("Elige una opcion para jugar: \n");
		System.out.println("1. Quiero escribir una letra");
		System.out.println("2. ¡Quiero resolver!");
		System.out.println("3. Abandonar");
		System.out.println("*--------------------------------*");

		return entrada.nextInt();

	}

	public static void main(String[] args) {
		Scanner entrada = new Scanner(System.in);
		System.out.println("¿Cuál es tu nombre, valiente?");
		System.out.print("Mi nombre es... ");
		nombreJugador = entrada.nextLine();

		horca = new Horca();
		palabra = new Palabra();
		boolean noHaResueltoMal = true;
		System.out.println("\n\nBIEVENIDO AL AHORCADO DE IES SON FERRER");
		System.out.println("=======================================");
		palabra.elegirPalabra();

		while (!comprobarFinal() && noHaResueltoMal) {
			switch (elegirDelMenu()) {
			case 1:
				palabra.comprobarLetra(pedirLetra());
				mostrarProgreso();
				break;

			case 2:
				if (resolver()) {
					System.out.println("=============");
					System.out.println("¡Has ganado, " + nombreJugador + "!");
					System.out.println("=============");
					// Hacemos esta comprobación para una vez adivinada la
					// palabra, el juego pare.
					noHaResueltoMal = false;
				} else {
					System.out.println("Lo siento, has perdido...");
					noHaResueltoMal = false;
				}
				break;
			case 3:
				System.out.println("¡Eres un cobarde, " + nombreJugador + "!");
				System.exit(0);
			default:
				break;
			}
		}

	}

}