// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

/************************************************************/
/**
 * La clase principal, Partida. Contiene datos sobre la partida que está en curso, tambén tiene un método que es un contador de puntos del jugador.
 */
public class Partida {
	/**
	 * 
	 */
	private String nombreJugador;
	/**
	 * 
	 */
	private int puntaje;
	/**
	 * 
	 */
	private int limiteFrases;
	/**
	 * 
	 */
	private int tiempoPorFrase;

	/**
	 * Cuenta los puntos en la partida dependiendo del puntuaje
	 */
	public void contadorPuntos() {
	}

	/**
	 * 
	 */
	public void mostrarProgreso() {
	}

	/**
	 * 
	 * @return letra 
	 */
	public boolean pedirLetra() {
	}

	/**
	 * 
	 */
	public void resolver() {
	}

	/**
	 * 
	 * @return fin 
	 */
	public boolean comprobarFinal() {
	}
};
