// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ahorcado;

import java.util.*;

/************************************************************/
/**
 * La clase principal, Partida. Contiene datos sobre la partida que está en
 * curso, tambén tiene un método que es un contador de puntos del jugador.
 */
public class Partida {
	/**
	 * 
	 */
	private String nombreJugador;
	/**
	 * 
	 */
	private int puntaje;
	/**
	 * 
	 */
	private int limiteFrases;
	/**
	 * 
	 */
	private int tiempoPorFrase;
	/**
	 * 
	 */
	public static Horca horca;
	/**
	 * 
	 */
	public static Palabra palabra;

	/**
	 * Cuenta los puntos en la partida dependiendo del puntuaje.
	 */
	public void contadorPuntos() {
	}

	/**
	 * Muestra el estado de la horca y los resultados de la palabra.
	 */
	public static void mostrarProgreso() {

		horca.dibujar();
		palabra.mostrarResultados();
	}

	/**
	 * Solicita una letra al usuario.
	 * 
	 * @return letra
	 */
	public static char pedirLetra() {

		Scanner entrada = new Scanner(System.in);

		System.out.print("Introduce una letra: ");
		char letra = entrada.nextLine().charAt(0);

		return letra;
	}

	/**
	 * Pide la respuesta al jugador.
	 * 
	 * @return palabra true si el jugador ha acertado o false en caso contrario.
	 */
	public static boolean resolver() {
		Scanner entrada = new Scanner(System.in);

		System.out.print("Introduce la respuesta: ");
		return palabra.comprobarPalabra(entrada.nextLine());

	}

	/**
	 * Comprueba tanto si hemos agotado los fallos como si hemos acertado todas
	 * las letras.
	 * 
	 * @return fin true si hemos ganado o perdido, false si todavía jugamos.
	 */
	public static boolean comprobarFinal() {
		return horca.comprobarSiPerdido() || palabra.comprobarSiGanado();

	}

	public static int elegirDelMenu() {
		Scanner entrada = new Scanner(System.in);

		System.out.println("Elige una opcion: ");
		System.out.println("1. Letra");
		System.out.println("2. Resolver");
		System.out.println("3. Abandonar");
		return entrada.nextInt();

	}

	public static void main(String[] args) {

		horca = new Horca();
		palabra = new Palabra();
		boolean noHaResueltoMal = true;
		palabra.elegirPalabra();

		while (!comprobarFinal() && noHaResueltoMal) {
			switch (elegirDelMenu()) {
			case 1:
				palabra.comprobarLetra(pedirLetra());
				mostrarProgreso();
				break;
			case 2:
				if (resolver())
					System.out.println("¡Has ganado!");
				else {
					System.out.println("Lo siento, has perdido...");
					noHaResueltoMal = false;
				}
				break;
			case 3:
				System.exit(0);
			default:
				break;
			}
		}

	}
}
